version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: next
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: next
    schedule:
      interval: daily
